name: Run Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install
        run: npm install
      - name: Build
        run: gulp test
